name: Pulumi Deployment Dev

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deployment:
    name: Client Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing dependencies
        run: yarn install
        working-directory: ./client

      - name: Building a production release
        run: yarn build
        working-directory: ./client

      - uses: pulumi/actions@v1
        with:
          command: up
        env:
          PULUMI_ROOT: CCA.Deployment
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
